services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    environment:
      - MONGODB_URI=${MONGODB_URI}

  socketserver:
    build:
      context: .
      dockerfile: socket.Dockerfile

    ports:
      - "3001:3001"